server:
  host: "localhost"
  port: 8084

consul:
  address: "localhost:8500"
  datacenter: "dc1"

redis:
  address: "localhost:6379"
  password: ""
  db: 0

database:
  host: "localhost"
  port: 3306
  name: "resume_centre"
  user: "root"
  password: ""

jwt:
  secret: "your-secret-key"
  expire_hours: 24

logging:
  level: "info"
  format: "json"
