server:
  host: "0.0.0.0"
  port: 8081

consul:
  address: "consul:8500"
  datacenter: "dc1"

redis:
  address: "redis:6379"
  password: ""
  db: 0

database:
  host: "mysql"
  port: 3306
  name: "jobfirst"
  user: "jobfirst"
  password: "jobfirst123"

jwt:
  secret: "your-secret-key"
  expire_hours: 24

logging:
  level: "info"
  format: "json"
