#!/bin/bash

echo "=== 腾讯云容器镜像服务配置指南 ==="
echo ""
echo "请按照以下步骤配置GitHub Secrets："
echo ""
echo "1. 登录腾讯云控制台：https://console.cloud.tencent.com/"
echo "2. 进入容器镜像服务：https://console.cloud.tencent.com/tcr"
echo "3. 创建命名空间 'jobfirst'（如果不存在）"
echo "4. 创建镜像仓库："
echo "   - jobfirst-gateway"
echo "   - jobfirst-shared-infra" 
echo "   - jobfirst-user"
echo ""
echo "5. 获取访问凭证："
echo "   - 进入个人访问凭证页面"
echo "   - 创建新的访问凭证"
echo "   - 记录用户名和密码"
echo ""
echo "6. 在GitHub仓库中设置Secrets："
echo "   - 进入 Settings > Secrets and variables > Actions"
echo "   - 添加以下Secrets："
echo ""
echo "   TENCENT_CCR_USERNAME: 腾讯云容器镜像服务用户名"
echo "   TENCENT_CCR_PASSWORD: 腾讯云容器镜像服务密码"
echo ""
echo "7. 验证配置："
echo "   - 推送代码到develop分支"
echo "   - 检查CI/CD流水线是否成功"
echo ""
echo "=== 配置完成 ==="
