name: Go Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build Gateway
      working-directory: backend/gateway
      run: go build -v -o gateway enhanced_gateway_simple.go
      
    - name: Build Shared Infrastructure
      working-directory: backend/shared/infrastructure
      run: go build -v -o shared-infrastructure .
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go-binaries
        path: |
          backend/gateway/gateway
          backend/shared/infrastructure/shared-infrastructure
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: go-binaries
        
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.TENCENT_DEPLOY_SSH_KEY }}
        known_hosts: ${{ secrets.TENCENT_KNOWN_HOSTS }}
        
    - name: Deploy to Tencent Cloud
      run: |
        scp -i ~/.ssh/tencent_deploy_key -o StrictHostKeyChecking=no \
          gateway shared-infrastructure \
          ${{ secrets.TENCENT_USER }}@${{ secrets.TENCENT_STAGING_HOST }}:/opt/jobfirst/
        
    - name: Restart Service
      run: |
        ssh -i ~/.ssh/tencent_deploy_key -o StrictHostKeyChecking=no \
          ${{ secrets.TENCENT_USER }}@${{ secrets.TENCENT_STAGING_HOST }} "sudo systemctl restart jobfirst"