name: Go Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build Gateway
      working-directory: backend/gateway
      run: go build -v -o gateway enhanced_gateway_simple.go
      
    - name: Build Shared Infrastructure
      working-directory: backend/shared/infrastructure
      run: go build -v -o shared-infrastructure .
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go-binaries
        path: |
          backend/gateway/gateway
          backend/shared/infrastructure/shared-infrastructure
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: go-binaries
        
    - name: Deploy to Tencent Cloud
      run: |
        echo "Deploying to Tencent Cloud..."
        echo "Build artifacts:"
        ls -la gateway shared-infrastructure || echo "Artifacts not found"
        echo "Deployment completed successfully (simulated)"
        echo "In production, this would deploy using SCP to Tencent Cloud"
        
    - name: Restart Service
      run: |
        echo "Restarting services..."
        echo "Service restart completed successfully (simulated)"
        echo "In production, this would restart services on Tencent Cloud"